
# create an alpine image with bash, Hashicorp Vault
FROM vault as vaultupdated
RUN apk --no-cache upgrade

FROM vaultupdated
# required for vault token create -id
USER root
WORKDIR tmp
COPY vault-DEV-config .
RUN vault policy write ULYSSE-developer ./ULYSSE-developer.hcl && \
    vault policy write ULYSSE-operation ./ULYSSE-operation.hcl && \
    vault policy write ULYSSE-servers ./ULYSSE-servers.hcl && \
    vault policy write ULYSSE-server-prod ./ULYSSE-server-prod.hcl && \
    vault kv put secret/DIGIT/ULYSSE/dev password=my-long-password-dev && \
    vault kv put secret/DIGIT/ULYSSE/test password=my-long-password-test && \
    vault kv put secret/DIGIT/ULYSSE/acc password=my-long-password-acc && \
    vault kv put secret/DIGIT/ULYSSE/prod password=my-long-password-prod && \
    vault token create -id dev -policy=ULYSSE-developer -display-name Developers && \
    vault token create -id ops policy=ULYSSE-operation -display-name Operational Team && \
    vault token create -id dc -policy=ULYSSE-servers -display-name DC && \
    vault token create -id dcPROD -policy=ULYSSE-server-prod -display-name DC PROD
